name: Deploy Vite App to GitHub Pages

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      - name: Delete Previous Tag (keep latest only if more than one)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
      
          # Liste des tags triés par date de création (annotated ou lightweight)
          TAGS=($(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags))
      
          # Vérifie s’il y a au moins 2 tags
          if [[ ${#TAGS[@]} -ge 2 ]]; then
            PREVIOUS_TAG=${TAGS[1]}
            echo "Deleting previous tag: $PREVIOUS_TAG"
            git push origin --delete "$PREVIOUS_TAG"
          else
            echo "Only one tag found. Skipping deletion."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}